version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=streaming_catalog_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - bundle_gems:/usr/local/bundle
      - ./backend/tmp:/app/tmp
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=streaming_catalog_development
    depends_on:
      - db
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle check || bundle install && bundle exec puma -C config/puma.rb"

volumes:
  postgres_data:
  bundle_gems:
